name: nexquub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  docx_to_text: ^1.0.1
  extended_image: ^10.0.1
  file_picker: ^10.1.2
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  flutter_pdf_text:
    git:
      url: https://github.com/gabbygreat/flutter_pdf_text.git
      ref: master
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  keyboard_actions: ^4.2.0
  lottie: ^3.2.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  signals: ^6.0.2
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.9

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/animation/

  fonts:
    - family: PlusJakartaSans
      fonts:

        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Italic.ttf
          weight: 400
          style: italic
        
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
      
    - family: ApfelGrotezk
      fonts:
        - asset: assets/fonts/ApfelGrotezk/ApfelGrotezk-Regular.otf
          weight: 400
        - asset: assets/fonts/ApfelGrotezk/ApfelGrotezk-Mittel.otf
          weight: 500
        - asset: assets/fonts/ApfelGrotezk/ApfelGrotezk-Satt.otf
          weight: 600
        - asset: assets/fonts/ApfelGrotezk/ApfelGrotezk-Fett.otf
          weight: 700
        - asset: assets/fonts/ApfelGrotezk/ApfelGrotezk-Brukt.otf
          weight: 800
