// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpnC2lYdCZmh5f5kr7bJCjZ0vB9_dGWdc',
    appId: '1:891417909143:web:252201ddb37947308896d2',
    messagingSenderId: '891417909143',
    projectId: 'nexquub',
    authDomain: 'nexquub.firebaseapp.com',
    storageBucket: 'nexquub.firebasestorage.app',
    measurementId: 'G-1NX68P1RB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMqbmKczLQKXwOWCmEd6LuCHZiw-NbAOM',
    appId: '1:891417909143:android:0d0040c66bb3d8158896d2',
    messagingSenderId: '891417909143',
    projectId: 'nexquub',
    storageBucket: 'nexquub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTN5BC_C55cvWL8WTvAOr4g20XyYeahJw',
    appId: '1:891417909143:ios:ceaf5078ae916e038896d2',
    messagingSenderId: '891417909143',
    projectId: 'nexquub',
    storageBucket: 'nexquub.firebasestorage.app',
    iosBundleId: 'com.nexquub.mobile.nexquub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTN5BC_C55cvWL8WTvAOr4g20XyYeahJw',
    appId: '1:891417909143:ios:ceaf5078ae916e038896d2',
    messagingSenderId: '891417909143',
    projectId: 'nexquub',
    storageBucket: 'nexquub.firebasestorage.app',
    iosBundleId: 'com.nexquub.mobile.nexquub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpnC2lYdCZmh5f5kr7bJCjZ0vB9_dGWdc',
    appId: '1:891417909143:web:e4e2c8a5613d98a18896d2',
    messagingSenderId: '891417909143',
    projectId: 'nexquub',
    authDomain: 'nexquub.firebaseapp.com',
    storageBucket: 'nexquub.firebasestorage.app',
    measurementId: 'G-30VF4J57ZW',
  );
}
